# _config.yml
title: “Aidan Baker”  
email: your.email@example.com  
description: “Data Scientist | Machine Learning | Visualization”  

# enable collections
collections:
  projects:
    output: true

# plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
